

                                             ------- CREATE TABELS ----

-- 1) EMPLOYEE TABLE:-

CREATE TABLE EMPLOYEE(
Employee_ID VARCHAR(50) PRIMARY KEY,
LAST_NAME CHAR (50),
FIRST_NAME CHAR (50),
TITLE VARCHAR (50),
REPORTS_TO VARCHAR (30),
LEVELS VARCHAR (10),
BIRTHDATE TIMESTAMP,
HIRE_DATE DATE,
ADDRESS VARCHAR (120),
CITY VARCHAR (50),
STATE VARCHAR (50),
COUNTRY VARCHAR (50), 
POSTAL_CODE VARCHAR (30),
PHONE VARCHAR (30),
FAX VARCHAR (30),
EMAIL VARCHAR (30));

											 
-- 2) CUSTOMER TABLE:-

CREATE TABLE CUSTOMER (
CUSTOMER_ID VARCHAR(30) PRIMARY KEY,
FIRST_NAME CHAR(30),
LAST_NAME CHAR (30),
COMPANY VARCHAR (30),
ADDRESS VARCHAR (30),
CITY VARCHAR (30),
STATE VARCHAR (30),
COUNTRY VARCHAR (30),
POSTAL_CODE INT,
PHONE INT,
FAX INT,
EMAIL VARCHAR (30),
SUPPORT_REP_ID VARCHAR (30)); 


-- 3) INVOICE TABLE :-

CREATE TABLE INVOICE (
INVOICE_ID VARCHAR (30) PRIMARY KEY,
CUSTOMER_ID VARCHAR (30),
INVOICE_DATE TIMESTAMP,
BILLING_ADDRESS VARCHAR (120),
BILLING_CITY VARCHAR (30),
BILLING_STATE VARCHAR (30),
BILLING_COUNTRY VARCHAR (30),
BILLING_POSTAL VARCHAR (30),
TOTAL FLOAT);


-- 4) INVOICE LINE TABLE :-

CREATE TABLE INVOICE_LINE (
INVOICE_LINE_ID VARCHAR (50) PRIMARY KEY,
INVOICE_ID VARCHAR (30),
TRACK_ID VARCHAR (30),
UNIT_PRICE VARCHAR (30),
QUANTITY VARCHAR (30));



-- 5) TRACK TABLE :-

CREATE TABLE TRACK (
TRACK_ID VARCHAR (50) PRIMARY KEY,
NAME VARCHAR (30),
ALBUM_ID VARCHAR (30),
MEDIA_TYPE_ID VARCHAR (30),
GENRE_ID VARCHAR (30),
COMPOSER VARCHAR (30),
MILLISECONDS TIMESTAMP,
BYTES INT,
UNIT_PRICE INT);


-- 6) PLAYLIST TABLE :-

CREATE TABLE PLAYLIST (
PLAYLIST_ID VARCHAR (50) PRIMARY KEY,
NAME VARCHAR (30));


-- 7) PLAYLIST_TRACK TABLE :-

CREATE TABLE PLAYLIST_TRACK (
PLAYLIST_ID VARCHAR (50) PRIMARY KEY,
TRACK_ID VARCHAR (50));


-- 8) ARTIST TABLE :-

CREATE TABLE ARTIST (
ARTIST_ID VARCHAR (50) PRIMARY KEY,
NAME VARCHAR (30));

 
-- 9) ALBUM TABLE:-

CREATE TABLE ALBUM (
ALBUM_ID VARCHAR (50) PRIMARY KEY,
TITLE VARCHAR (30),
ARTIST_ID VARCHAR (30));


-- 10) MEDIA_TYRE TABLE :-

CREATE TABLE MEDIA_TYPE (
MEDIA_TYPE_ID VARCHAR (50) PRIMARY KEY,
NAME VARCHAR (30));


-- 11) GENRE TABLE :-

CREATE TABLE GENRE (
GENRE_ID VARCHAR (50) PRIMARY KEY,
NAME VARCHAR (30));




